### ISSUE TITLE
[IDEA] Checkboxes instead of data

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/Mesures-Website#26]
**If your idea is related to a problem you had, what is it?**
It has been hard to program the data correctly. If I must do it, I can continue doing it, but I would prefer not to.

**Describe the solution you'd like**
Checkboxes, something like this, where you can check and uncheck the boxes:
- [x] 2023
  - [x] December
    - [x] Challenge 1
    - [x] Challenge 2
    - [x] Challenge 3
- [ ] 2024
  - [x] March
    - [x] Challenge 1
    - [x] Challenge 2
    - [x] Challenge 3
  - [ ] August
    - [x] Challenge 1
    - [ ] Challenge 2
    - [ ] Challenge 3

You will be able to check years and months too, which will check all of the challenges inside of them.

**Advantages**
* You can choose to skip challenges that you want to skip.
* It is still easy to copy your progress from another device.
* It is more user friendly and looks cleaner.

**Disadvantages**
* It takes slightly more time to copy your progress from another device.
* It doesn't look as *"cool"* and *"modern"*.
* It doesn't copy your username and seed too, so you have to manually do that.

**Describes alternatives**
Use data, like is already planned.

**Additional context**
It would make it a lot easier to make!

**Comment by BeepBot99** [comment]
Oh, by the way, please don't click on any of the checkboxes above.

**Comment by Mesure73L** [comment]
The reason for using data (as mentioned) is it's easier to copy from device to device, which is the whole point in this. Using the checkboxes makes it so much easier to hack and say you completed all of them.

> You can choose to skip challenges that you want to skip.

No challenge will ever be locked for the reason of previous challenges being incomplete. If you are struggling with a challenge, then you can go to a different challenge first and give your mind a break, unlike Advent of Code.

> It is more user friendly and looks cleaner.

It will get really messy after a few years, because it will have a lot of checkboxes on the page and it might take a while to load on low-end devices.

> Oh, by the way, please don't click on any of the checkboxes above.

Too late, I clicked on the checkbox before I saw that.

Unfortunately this solution to the data input not working (issue #15) is not a good idea, if you really don't want to make the data input then please provide other alternate solutions.
