### ISSUE TITLE
Access to Twelve of Code settings needed to continue development

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/Mesures-Website#43]
### Issue Contents

Please initialize settings, even if the data import doesn't work. I need access to be able to change my seed.

**Comment by BeepBot99** [comment]
I will make settings back up and running where you can change the username and seed, but not the data yet.
I will finish this as soon as possible, probably tonight.
However, note that currently, it is still possible to change the seed programmatically by setting `cman.seed = newSeedValueAsString`. Since you do not have access to the DevTools console right now, you could create a `promt()` that asks you for the new seed when a button is pressed and sets it.
Although, note that this is just a temporary fix. Do not commit it to the `main` branch.
I will make a permenant fix tonight,
